USE conversation_globale;
DROP TABLE IF EXISTS conversations;

CREATE TABLE conversations (
    CONVERSATION_RATING TEXT,
    CREATED_AT DATETIME,
    ID BIGINT PRIMARY KEY,
    OPEN BOOLEAN,
    PRIORITY VARCHAR(50),
    `READ` BOOLEAN,
    STATE VARCHAR(50),
    TAGS TEXT,
    TYPE VARCHAR(50),
    UPDATED_AT DATETIME,
    WAITING_SINCE DATETIME,
    _SDC_BATCHED_AT DATETIME,
    _SDC_EXTRACTED_AT DATETIME,
    _SDC_RECEIVED_AT DATETIME,
    _SDC_SEQUENCE BIGINT,
    _SDC_TABLE_VERSION INT,
    ASSIGNEE TEXT,
    SNOOZED_UNTIL DATETIME
);


DROP TABLE IF EXISTS conversation_parts;

CREATE TABLE conversation_parts (
    ASSIGNED_TO TEXT,
    ATTACHMENTS TEXT,
    AUTHOR TEXT,
    CONVERSATION_CREATED_AT DATETIME,
    CONVERSATION_ID BIGINT,
    CONVERSATION_UPDATED_AT DATETIME,
    CREATED_AT DATETIME,
    ID BIGINT PRIMARY KEY,
    NOTIFIED_AT DATETIME,
    PART_GROUP VARCHAR(50),
    `TYPE` VARCHAR(50),
    UPDATED_AT DATETIME,
    _SDC_BATCHED_AT DATETIME,
    _SDC_EXTRACTED_AT DATETIME,
    _SDC_RECEIVED_AT DATETIME,
    _SDC_SEQUENCE BIGINT,
    _SDC_TABLE_VERSION INT
);



